/**
 * Integration tests for local proxy server and routing
 */
import test from "node:test";
import assert from "node:assert/strict";
import http from "node:http";
import { startProxy, isProxyAlive, sanitizeHeaders } from "../src/proxy.ts";
import { ALL_MODELS } from "../src/models.ts";

test("proxy starts, responds to /v1/models, and shuts down cleanly", async () => {
	const testPort = 19180;
	const { server, port } = await startProxy(testPort);
	assert.ok(server);
	assert.equal(port, testPort);

	try {
		// Probe /v1/models
		const isAlive = await isProxyAlive(testPort);
		assert.equal(isAlive, true);

		// Fetch catalog from proxy
		const res = await fetch(`http://127.0.0.1:${testPort}/v1/models`);
		assert.equal(res.status, 200);
		const json = await res.json() as { object: string; data: Array<{ id: string }> };
		assert.equal(json.object, "list");
		assert.ok(Array.isArray(json.data));
		assert.ok(json.data.length > 0);

		// Test 405 on disallowed method
		const putRes = await fetch(`http://127.0.0.1:${testPort}/v1/models`, {
			method: "PUT",
		});
		assert.equal(putRes.status, 405);

		// Test 404 on unknown path (fetch normalizes "..", so /v1/../admin → /admin → unknown)
		const trapRes = await fetch(`http://127.0.0.1:${testPort}/v1/../admin`);
		assert.equal(trapRes.status, 404);
		// Test server is unref'd so CLI commands like omp plugin install exit cleanly
		// In Node.js, an unref'd server has its underlying handle unref'd.
		// We can verify fetch still succeeds on unref server:
		const modelsRes = await fetch(`http://127.0.0.1:${testPort}/v1/models`);
		assert.equal(modelsRes.status, 200);
	} finally {
		await new Promise<void>((resolve) => server.close(() => resolve()));
	}
});

test("proxy rejects oversized bodies with 413 before buffering", async () => {
	const testPort = 19181;
	const { server, port } = await startProxy(testPort);
	assert.ok(server);
	try {
		// Raw request: declare a >32MB content-length. undici's fetch refuses
		// mismatched lengths, so use node:http directly — the server must 413
		// on the declared size without waiting for the body.
		const response = await new Promise<http.IncomingMessage>((resolve, reject) => {
			const req = http.request(
				{
					host: "127.0.0.1",
					port,
					path: "/v1/chat/completions",
					method: "POST",
					headers: {
						"content-type": "application/json",
						"content-length": String(64 * 1024 * 1024),
					},
				},
				resolve,
			);
			req.on("error", reject);
			req.end("{}");
		});
		assert.equal(response.statusCode, 413, "declared oversized body must get 413");
		const chunks: Buffer[] = [];
		for await (const chunk of response) chunks.push(chunk as Buffer);
		const json = JSON.parse(Buffer.concat(chunks).toString()) as { error: string };
		assert.equal(json.error, "payload too large");
	} finally {
		await new Promise<void>((resolve) => server.close(() => resolve()));
	}
});

test("proxy OPTIONS preflight returns 204 without CORS headers", async () => {
	const testPort = 19182;
	const { server, port } = await startProxy(testPort);
	assert.ok(server);
	try {
		const res = await fetch(`http://127.0.0.1:${port}/v1/models`, { method: "OPTIONS" });
		assert.equal(res.status, 204);
		assert.equal(
			res.headers.get("access-control-allow-origin"),
			null,
			"wildcard CORS header must not be reflected",
		);
		assert.equal(res.headers.get("access-control-allow-methods"), null);
	} finally {
		await new Promise<void>((resolve) => server.close(() => resolve()));
	}
});

test("sanitizeHeaders forwards only allowlisted headers", () => {
	const fwd = sanitizeHeaders(
		{
			host: "127.0.0.1:28180",
			"content-type": "application/json",
			accept: "application/json",
			authorization: "Bearer client-token",
			"x-request-id": "req-123",
			"x-opencode-session": "sess-1",
			"x-relay-auth": "secret",
			"x-forwarded-for": "203.0.113.9",
			cookie: "session=abc",
			"user-agent": "node",
		},
		"opencode.ai",
	);
	assert.equal(fwd["content-type"], "application/json");
	assert.equal(fwd.accept, "application/json");
	assert.equal(fwd.authorization, "Bearer client-token");
	assert.equal(fwd["x-request-id"], "req-123");
	// Client x-opencode-* headers pass the allowlist but are replaced by the
	// proxy's own generated headers (opencodeHeaders wins, no duplicates).
	assert.equal(
		fwd["x-opencode-client"],
		"cli",
		"x-opencode-* headers are regenerated by the proxy",
	);
	assert.equal(fwd["x-relay-auth"], undefined, "client x-relay-auth must be dropped");
	assert.equal(fwd["x-forwarded-for"], undefined, "x-forwarded-for must be dropped");
	assert.equal(fwd.cookie, undefined, "cookie must be dropped");
	assert.equal(fwd.host, "opencode.ai", "host must be replaced with target");
});
